spring:  application:    name: customer-service  config:    import: configserver:http://localhost:8888
management:  endpoints:    web:      exposure:        include:        - "*"        server:  port: 4050          